<?php

namespace ContainerSTI16y2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DhwZj0nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DhwZj0n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DhwZj0n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PatientController::delete' => ['privates', '.service_locator.mk9shxU', 'get_ServiceLocator_Mk9shxUService', true],
            'App\\Controller\\PatientController::deleteImage' => ['privates', '.service_locator.XBdMERO', 'get_ServiceLocator_XBdMEROService', true],
            'App\\Controller\\PatientController::edit' => ['privates', '.service_locator.mk9shxU', 'get_ServiceLocator_Mk9shxUService', true],
            'App\\Controller\\PatientController::show' => ['privates', '.service_locator.mk9shxU', 'get_ServiceLocator_Mk9shxUService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.IlsK1Cj', 'get_ServiceLocator_IlsK1CjService', true],
            'App\\Controller\\SearchController::searchPatient' => ['privates', '.service_locator.XupNM.k', 'get_ServiceLocator_XupNM_KService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::editRole' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController::mespatients' => ['privates', '.service_locator.XupNM.k', 'get_ServiceLocator_XupNM_KService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\PatientController:delete' => ['privates', '.service_locator.mk9shxU', 'get_ServiceLocator_Mk9shxUService', true],
            'App\\Controller\\PatientController:deleteImage' => ['privates', '.service_locator.XBdMERO', 'get_ServiceLocator_XBdMEROService', true],
            'App\\Controller\\PatientController:edit' => ['privates', '.service_locator.mk9shxU', 'get_ServiceLocator_Mk9shxUService', true],
            'App\\Controller\\PatientController:show' => ['privates', '.service_locator.mk9shxU', 'get_ServiceLocator_Mk9shxUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.IlsK1Cj', 'get_ServiceLocator_IlsK1CjService', true],
            'App\\Controller\\SearchController:searchPatient' => ['privates', '.service_locator.XupNM.k', 'get_ServiceLocator_XupNM_KService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:editRole' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController:mespatients' => ['privates', '.service_locator.XupNM.k', 'get_ServiceLocator_XupNM_KService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\PatientController::delete' => '?',
            'App\\Controller\\PatientController::deleteImage' => '?',
            'App\\Controller\\PatientController::edit' => '?',
            'App\\Controller\\PatientController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SearchController::searchPatient' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::editRole' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::mespatients' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PatientController:delete' => '?',
            'App\\Controller\\PatientController:deleteImage' => '?',
            'App\\Controller\\PatientController:edit' => '?',
            'App\\Controller\\PatientController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SearchController:searchPatient' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:editRole' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:mespatients' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
