<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUiPz4Y4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUiPz4Y4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUiPz4Y4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUiPz4Y4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUiPz4Y4\App_KernelDevDebugContainer([
    'container.build_hash' => 'UiPz4Y4',
    'container.build_id' => '29e2c4c8',
    'container.build_time' => 1625218609,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUiPz4Y4');
