<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBXYoH5J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBXYoH5J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBXYoH5J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBXYoH5J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBXYoH5J\App_KernelDevDebugContainer([
    'container.build_hash' => 'BXYoH5J',
    'container.build_id' => 'da58636b',
    'container.build_time' => 1626047888,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBXYoH5J');
